"""充电桩测试数据"""

# 新增充电桩测试数据
CHARGING_PILE_ADD_TEST_DATA = [
    {
        "title": "冒烟-完整填写所有字段提交成功",
        "data": {
            "charging_pile_name": "自动化测试充电桩001",
            "street_index": 0,
            "address_index": 0,
            "place_type": "公共充电站",
            "operator": "测试运营商",
            "service_phone": "400-1234-5678",
            "total_piles": 10,
            "fast_piles": 5,
            "slow_piles": 5,
            "interface_standard": "GB/T",
            "parking_nature": "公共停车场",
            "charging_fee": "1.5",
            "payment_method": "微信支付",
            "operational_status": "运营中",
            "service_hours": "全天24小时",
            "facilities": "卫生间,休息室",
            "maintenance_contact": "张三",
        },
        "expect_success": True,
        "validation_info": None,
    },
    {
        "title": "正向-只填写必填字段提交成功",
        "data": {
            "charging_pile_name": "必填字段测试桩",
            "street_index": 0,
            "address_index": 0,
            "place_type": "公共充电站",
            "operator": None,
            "service_phone": None,
            "total_piles": None,
            "fast_piles": None,
            "slow_piles": None,
            "interface_standard": None,
            "parking_nature": None,
            "charging_fee": None,
            "payment_method": None,
            "operational_status": None,
            "service_hours": None,
            "facilities": None,
            "maintenance_contact": None,
        },
        "expect_success": True,
        "validation_info": None,
    },
    {
        "title": "正向-填写部分非必填字段提交成功",
        "data": {
            "charging_pile_name": "部分字段测试桩",
            "street_index": 0,
            "address_index": 0,
            "place_type": "公共充电站",
            "operator": "部分测试运营商",
            "service_phone": "400-8888-9999",
            "total_piles": 20,
            "fast_piles": None,
            "slow_piles": None,
            "interface_standard": None,
            "parking_nature": None,
            "charging_fee": None,
            "payment_method": None,
            "operational_status": None,
            "service_hours": None,
            "facilities": None,
            "maintenance_contact": None,
        },
        "expect_success": True,
        "validation_info": None,
    },
    {
        "title": "反向-点位/桩群名称为空",
        "data": {
            "charging_pile_name": "",
            "street_index": 0,
            "address_index": 0,
            "place_type": None,
            "operator": None,
            "service_phone": None,
            "total_piles": None,
            "fast_piles": None,
            "slow_piles": None,
            "interface_standard": None,
            "parking_nature": None,
            "charging_fee": None,
            "payment_method": None,
            "operational_status": None,
            "service_hours": None,
            "facilities": None,
            "maintenance_contact": None,
        },
        "expect_success": False,
        "validation_info": {
            "selector": "input[placeholder*='点位']",
            "trigger": "blur",
            "expected_error_text": "请输入",
        },
    },
    {
        "title": "反向-街道为空",
        "data": {
            "charging_pile_name": "测试充电桩",
            "street_index": None,
            "address_index": 0,
            "place_type": None,
            "operator": None,
            "service_phone": None,
            "total_piles": None,
            "fast_piles": None,
            "slow_piles": None,
            "interface_standard": None,
            "parking_nature": None,
            "charging_fee": None,
            "payment_method": None,
            "operational_status": None,
            "service_hours": None,
            "facilities": None,
            "maintenance_contact": None,
        },
        "expect_success": False,
        "validation_info": {
            "selector": "input[placeholder*='街道']",
            "trigger": "submit",
            "expected_error_text": "请选择",
        },
    },
    {
        "title": "反向-详细地址为空",
        "data": {
            "charging_pile_name": "测试充电桩",
            "street_index": 0,
            "address_index": None,
            "place_type": None,
            "operator": None,
            "service_phone": None,
            "total_piles": None,
            "fast_piles": None,
            "slow_piles": None,
            "interface_standard": None,
            "parking_nature": None,
            "charging_fee": None,
            "payment_method": None,
            "operational_status": None,
            "service_hours": None,
            "facilities": None,
            "maintenance_contact": None,
        },
        "expect_success": False,
        "validation_info": {
            "selector": "input[placeholder*='详细地址']",
            "trigger": "submit",
            "expected_error_text": "请选择",
        },
    },
    {
        "title": "反向-点位/桩群名称超过最大长度",
        "data": {
            "charging_pile_name": "a" * 101,
            "street_index": 0,
            "address_index": 0,
            "place_type": None,
            "operator": None,
            "service_phone": None,
            "total_piles": None,
            "fast_piles": None,
            "slow_piles": None,
            "interface_standard": None,
            "parking_nature": None,
            "charging_fee": None,
            "payment_method": None,
            "operational_status": None,
            "service_hours": None,
            "facilities": None,
            "maintenance_contact": None,
        },
        "expect_success": False,
        "validation_info": {
            "selector": "input[placeholder*='点位']",
            "trigger": "blur",
            "expected_error_text": "最大长度",
        },
    },
    {
        "title": "反向-服务电话格式错误",
        "data": {
            "charging_pile_name": "格式错误测试桩",
            "street_index": 0,
            "address_index": 0,
            "place_type": None,
            "operator": None,
            "service_phone": "12345",
            "total_piles": None,
            "fast_piles": None,
            "slow_piles": None,
            "interface_standard": None,
            "parking_nature": None,
            "charging_fee": None,
            "payment_method": None,
            "operational_status": None,
            "service_hours": None,
            "facilities": None,
            "maintenance_contact": None,
        },
        "expect_success": False,
        "validation_info": {
            "selector": "input[placeholder*='服务电话']",
            "trigger": "blur",
            "expected_error_text": "格式",
        },
    },
    {
        "title": "反向-充电桩总数输入负数",
        "data": {
            "charging_pile_name": "负数测试桩",
            "street_index": 0,
            "address_index": 0,
            "place_type": None,
            "operator": None,
            "service_phone": None,
            "total_piles": -5,
            "fast_piles": None,
            "slow_piles": None,
            "interface_standard": None,
            "parking_nature": None,
            "charging_fee": None,
            "payment_method": None,
            "operational_status": None,
            "service_hours": None,
            "facilities": None,
            "maintenance_contact": None,
        },
        "expect_success": False,
        "validation_info": {
            "selector": "input[placeholder*='充电桩总数']",
            "trigger": "blur",
            "expected_error_text": "正数",
        },
    },
]

# 充电桩搜索测试数据
CHARGING_PILE_SEARCH_TEST_DATA = [
    {
        "title": "正向-按点位/桩群名称精确搜索",
        "data": {
            "charging_pile_name": "自动化测试充电桩001",
        },
        "expect_success": True,
        "expect_count": 1,
    },
    {
        "title": "正向-按运营商/品牌搜索",
        "data": {
            "operator": "测试运营商",
        },
        "expect_success": True,
        "expect_count": 1,
    },
    {
        "title": "正向-组合条件搜索",
        "data": {
            "charging_pile_name": "自动化测试",
            "operator": "测试",
        },
        "expect_success": True,
        "expect_count": 1,
    },
    {
        "title": "正向-搜索结果为空",
        "data": {
            "charging_pile_name": "不存在的充电桩名称",
        },
        "expect_success": False,
        "expect_count": 0,
    },
]

# 充电桩编辑测试数据
CHARGING_PILE_EDIT_TEST_DATA = [
    {
        "title": "正向-编辑修改点位/桩群名称",
        "data": {
            "charging_pile_name": "编辑后充电桩名称",
            "street_index": None,
            "address_index": None,
            "place_type": None,
            "operator": "编辑测试运营商",
            "service_phone": None,
            "total_piles": None,
            "fast_piles": None,
            "slow_piles": None,
            "interface_standard": None,
            "parking_nature": None,
            "charging_fee": None,
            "payment_method": None,
            "operational_status": None,
            "service_hours": None,
            "facilities": None,
            "maintenance_contact": None,
        },
        "expect_success": True,
    },
    {
        "title": "正向-编辑清空非必填字段",
        "data": {
            "charging_pile_name": None,
            "street_index": None,
            "address_index": None,
            "place_type": None,
            "operator": "",
            "service_phone": "",
            "total_piles": None,
            "fast_piles": None,
            "slow_piles": None,
            "interface_standard": None,
            "parking_nature": None,
            "charging_fee": None,
            "payment_method": None,
            "operational_status": None,
            "service_hours": None,
            "facilities": None,
            "maintenance_contact": "",
        },
        "expect_success": True,
    },
]
